# Generated by Django 5.2.7 on 2025-11-16 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividadEconomica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_detalle', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidad_medida', models.CharField(choices=[('UNI', 'Unidad'), ('KG', 'Kilogramo'), ('LT', 'Litro'), ('M', 'Metro'), ('M2', 'Metro cuadrado'), ('M3', 'Metro cúbico'), ('HR', 'Hora'), ('JG', 'Juego'), ('PAQ', 'Paquete'), ('DOC', 'Docena'), ('KW', 'Kilowatt'), ('TN', 'Tonelada'), ('PAR', 'Par'), ('CJ', 'Caja'), ('BOB', 'Bobina')], max_length=4)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividadEconomica.producto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividadEconomica.servicio')),
            ],
        ),
    ]
