# Generated by Django 5.2.7 on 2025-11-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalleIngreso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleingreso',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
