# Generated by Django 5.2.7 on 2025-11-09 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividadEconomica', '0002_initial'),
        ('detalleIngreso', '0001_initial'),
        ('transaccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleingreso',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingreso', to='transaccion.ingreso'),
        ),
        migrations.AddField(
            model_name='detalleingreso',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto', to='actividadEconomica.producto'),
        ),
        migrations.AddField(
            model_name='detalleingreso',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicio', to='actividadEconomica.servicio'),
        ),
        migrations.AddField(
            model_name='detalleingreso',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detalleIngreso.unidadmedida'),
        ),
    ]
