# Generated by Django 5.2.7 on 2025-11-21 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalleIngreso', '0002_alter_detalleingreso_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleingreso',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
