# Generated by Django 5.2.7 on 2025-11-16 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividadEconomica', '0001_initial'),
        ('emprendimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='emprendimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='emprendimiento.emprendimiento'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='actividadEconomica.categoria'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='emprendimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='emprendimiento.emprendimiento'),
        ),
    ]
