# Generated by Django 5.2.7 on 2025-10-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('FA', 'Factura A'), ('FB', 'Factura B'), ('FC', 'Factura C'), ('NC', 'Nota de Crédito'), ('ND', 'Nota de Débito'), ('RC', 'Recibo'), ('RM', 'Remito'), ('OT', 'Otro')], default='FB', max_length=2)),
                ('medio_pago', models.CharField(choices=[('EF', 'Efectivo'), ('TC', 'Tarjeta de Crédito'), ('TD', 'Tarjeta de Débito'), ('TR', 'Transferencia'), ('QR', 'Pago QR'), ('MD', 'Pago MODO'), ('MP', 'Mercado Pago'), ('CH', 'Cheque'), ('OT', 'Otro')], default='EF', max_length=2)),
            ],
        ),
    ]
