# Generated by Django 5.2.7 on 2025-11-09 18:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comprobante', '0001_initial'),
        ('emprendimiento', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=9)),
                ('descripcion', models.CharField(max_length=100)),
                ('comprobante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos', to='comprobante.comprobante')),
                ('emprendimiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos', to='emprendimiento.emprendimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=9)),
                ('descripcion', models.CharField(max_length=100)),
                ('comprobante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='comprobante.comprobante')),
                ('emprendimiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='emprendimiento.emprendimiento')),
            ],
        ),
    ]
