# Generated by Django 5.2.7 on 2025-11-16 20:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comprobante', '0001_initial'),
        ('detalleIngreso', '0001_initial'),
        ('emprendimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=9)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipoTrx', models.CharField(choices=[('IN', 'Ingreso'), ('EG', 'Egreso')], default='IN', max_length=2)),
                ('comprobante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trx', to='comprobante.comprobante')),
                ('detalle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trx', to='detalleIngreso.detalleingreso')),
                ('emprendimiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trx', to='emprendimiento.emprendimiento')),
            ],
        ),
    ]
