# Generated by Django 5.2.7 on 2025-11-21 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalleIngreso', '0003_alter_detalleingreso_fecha_creacion'),
        ('transaccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='detalle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trx', to='detalleIngreso.detalleingreso'),
        ),
    ]
