# Generated by Django 5.2.7 on 2025-11-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('owner', 'Dueño'), ('marketing', 'Marketing'), ('finanzas', 'Finanzas')], default='owner', max_length=10),
        ),
    ]
